/* tslint:disable */
/* eslint-disable */
/**
 * Endaoment API
 * The official Endaoment API & SDK endpoints
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  NdaoSdkDonationSwap,
  NdaoSdkFund,
  NdaoSdkOrg,
  NdaoSdkTransaction,
} from '../models';
import {
    NdaoSdkDonationSwapFromJSON,
    NdaoSdkDonationSwapToJSON,
    NdaoSdkFundFromJSON,
    NdaoSdkFundToJSON,
    NdaoSdkOrgFromJSON,
    NdaoSdkOrgToJSON,
    NdaoSdkTransactionFromJSON,
    NdaoSdkTransactionToJSON,
} from '../models';

export interface GetDeployedOrgsRequest {
    count?: number;
    offset?: number;
}

export interface GetDonationSwapTransactionRequest {
    ein: string;
    amountIn: string;
    tokenContractAddress?: string;
}

export interface GetOrgDeployTransactionRequest {
    ein: string;
}

export interface GetVisibleFundsRequest {
    count?: number;
    offset?: number;
}

export interface SearchOrgsRequest {
    searchTerm?: string;
    nteeMajorCodes?: string;
    nteeMinorCodes?: string;
    deployedStatus?: SearchOrgsDeployedStatusEnum;
    count?: number;
    offset?: number;
}

export interface SearchVisibleFundsRequest {
    name: string;
    count?: number;
    offset?: number;
}

/**
 * 
 */
export class EndaomentSdkApi extends runtime.BaseAPI {

    /**
     * Only organizations that already have a deployed contract on Endaoment will be returned
     * Get a list of deployed Org contracts
     */
    async getDeployedOrgsRaw(requestParameters: GetDeployedOrgsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<NdaoSdkOrg>>> {
        const queryParameters: any = {};

        if (requestParameters.count !== undefined) {
            queryParameters['count'] = requestParameters.count;
        }

        if (requestParameters.offset !== undefined) {
            queryParameters['offset'] = requestParameters.offset;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/v1/sdk/orgs`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(NdaoSdkOrgFromJSON));
    }

    /**
     * Only organizations that already have a deployed contract on Endaoment will be returned
     * Get a list of deployed Org contracts
     */
    async getDeployedOrgs(requestParameters: GetDeployedOrgsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<NdaoSdkOrg>> {
        const response = await this.getDeployedOrgsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get the transaction information required to swap and donate a given token amount to an org
     */
    async getDonationSwapTransactionRaw(requestParameters: GetDonationSwapTransactionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NdaoSdkDonationSwap>> {
        if (requestParameters.ein === null || requestParameters.ein === undefined) {
            throw new runtime.RequiredError('ein','Required parameter requestParameters.ein was null or undefined when calling getDonationSwapTransaction.');
        }

        if (requestParameters.amountIn === null || requestParameters.amountIn === undefined) {
            throw new runtime.RequiredError('amountIn','Required parameter requestParameters.amountIn was null or undefined when calling getDonationSwapTransaction.');
        }

        const queryParameters: any = {};

        if (requestParameters.ein !== undefined) {
            queryParameters['ein'] = requestParameters.ein;
        }

        if (requestParameters.tokenContractAddress !== undefined) {
            queryParameters['tokenContractAddress'] = requestParameters.tokenContractAddress;
        }

        if (requestParameters.amountIn !== undefined) {
            queryParameters['amountIn'] = requestParameters.amountIn;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/v1/sdk/donations/swap`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NdaoSdkDonationSwapFromJSON(jsonValue));
    }

    /**
     * Get the transaction information required to swap and donate a given token amount to an org
     */
    async getDonationSwapTransaction(requestParameters: GetDonationSwapTransactionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NdaoSdkDonationSwap> {
        const response = await this.getDonationSwapTransactionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get the transaction information required to deploy a given org
     */
    async getOrgDeployTransactionRaw(requestParameters: GetOrgDeployTransactionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NdaoSdkTransaction>> {
        if (requestParameters.ein === null || requestParameters.ein === undefined) {
            throw new runtime.RequiredError('ein','Required parameter requestParameters.ein was null or undefined when calling getOrgDeployTransaction.');
        }

        const queryParameters: any = {};

        if (requestParameters.ein !== undefined) {
            queryParameters['ein'] = requestParameters.ein;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/v1/sdk/orgs/deploy`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NdaoSdkTransactionFromJSON(jsonValue));
    }

    /**
     * Get the transaction information required to deploy a given org
     */
    async getOrgDeployTransaction(requestParameters: GetOrgDeployTransactionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NdaoSdkTransaction> {
        const response = await this.getOrgDeployTransactionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Only community and transparent funds will be returned
     * Get a list of Endaoment funds
     */
    async getVisibleFundsRaw(requestParameters: GetVisibleFundsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<NdaoSdkFund>>> {
        const queryParameters: any = {};

        if (requestParameters.count !== undefined) {
            queryParameters['count'] = requestParameters.count;
        }

        if (requestParameters.offset !== undefined) {
            queryParameters['offset'] = requestParameters.offset;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/v1/sdk/funds`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(NdaoSdkFundFromJSON));
    }

    /**
     * Only community and transparent funds will be returned
     * Get a list of Endaoment funds
     */
    async getVisibleFunds(requestParameters: GetVisibleFundsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<NdaoSdkFund>> {
        const response = await this.getVisibleFundsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Note: If using multiple parameters, the search will perform an AND operation of all inputs
     * Get a list of Endaoment Orgs, filtered by search parameters
     */
    async searchOrgsRaw(requestParameters: SearchOrgsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<NdaoSdkOrg>>> {
        const queryParameters: any = {};

        if (requestParameters.searchTerm !== undefined) {
            queryParameters['searchTerm'] = requestParameters.searchTerm;
        }

        if (requestParameters.nteeMajorCodes !== undefined) {
            queryParameters['nteeMajorCodes'] = requestParameters.nteeMajorCodes;
        }

        if (requestParameters.nteeMinorCodes !== undefined) {
            queryParameters['nteeMinorCodes'] = requestParameters.nteeMinorCodes;
        }

        if (requestParameters.deployedStatus !== undefined) {
            queryParameters['deployedStatus'] = requestParameters.deployedStatus;
        }

        if (requestParameters.count !== undefined) {
            queryParameters['count'] = requestParameters.count;
        }

        if (requestParameters.offset !== undefined) {
            queryParameters['offset'] = requestParameters.offset;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/v1/sdk/orgs/search`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(NdaoSdkOrgFromJSON));
    }

    /**
     * Note: If using multiple parameters, the search will perform an AND operation of all inputs
     * Get a list of Endaoment Orgs, filtered by search parameters
     */
    async searchOrgs(requestParameters: SearchOrgsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<NdaoSdkOrg>> {
        const response = await this.searchOrgsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Only community and transparent funds will be returned
     * Get a list of Endaoment Funds, filtered by search paramenter
     */
    async searchVisibleFundsRaw(requestParameters: SearchVisibleFundsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<NdaoSdkFund>>> {
        if (requestParameters.name === null || requestParameters.name === undefined) {
            throw new runtime.RequiredError('name','Required parameter requestParameters.name was null or undefined when calling searchVisibleFunds.');
        }

        const queryParameters: any = {};

        if (requestParameters.name !== undefined) {
            queryParameters['name'] = requestParameters.name;
        }

        if (requestParameters.count !== undefined) {
            queryParameters['count'] = requestParameters.count;
        }

        if (requestParameters.offset !== undefined) {
            queryParameters['offset'] = requestParameters.offset;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/v1/sdk/funds/search`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(NdaoSdkFundFromJSON));
    }

    /**
     * Only community and transparent funds will be returned
     * Get a list of Endaoment Funds, filtered by search paramenter
     */
    async searchVisibleFunds(requestParameters: SearchVisibleFundsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<NdaoSdkFund>> {
        const response = await this.searchVisibleFundsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const SearchOrgsDeployedStatusEnum = {
    Deployed: 'deployed',
    Undeployed: 'undeployed',
    All: 'all'
} as const;
export type SearchOrgsDeployedStatusEnum = typeof SearchOrgsDeployedStatusEnum[keyof typeof SearchOrgsDeployedStatusEnum];
