/* tslint:disable */
/* eslint-disable */
/**
 * Endaoment API
 * The official Endaoment API & SDK endpoints
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DonationSwapDtoQuote } from './DonationSwapDtoQuote';
import {
    DonationSwapDtoQuoteFromJSON,
    DonationSwapDtoQuoteFromJSONTyped,
    DonationSwapDtoQuoteToJSON,
} from './DonationSwapDtoQuote';

/**
 * 
 * @export
 * @interface DonationSwapDto
 */
export interface DonationSwapDto {
    /**
     * The address this transaction will be sent to
     * @type {string}
     * @memberof DonationSwapDto
     */
    to: string;
    /**
     * The data this transaction will send to the destination contract
     * @type {string}
     * @memberof DonationSwapDto
     */
    data: string;
    /**
     * The ETH value, if any, this transaction will send along. This value will only be > 0 if performing an ETH donation
     * @type {string}
     * @memberof DonationSwapDto
     */
    value: string;
    /**
     * 
     * @type {DonationSwapDtoQuote}
     * @memberof DonationSwapDto
     */
    quote: DonationSwapDtoQuote;
}

/**
 * Check if a given object implements the DonationSwapDto interface.
 */
export function instanceOfDonationSwapDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "to" in value;
    isInstance = isInstance && "data" in value;
    isInstance = isInstance && "value" in value;
    isInstance = isInstance && "quote" in value;

    return isInstance;
}

export function DonationSwapDtoFromJSON(json: any): DonationSwapDto {
    return DonationSwapDtoFromJSONTyped(json, false);
}

export function DonationSwapDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): DonationSwapDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'to': json['to'],
        'data': json['data'],
        'value': json['value'],
        'quote': DonationSwapDtoQuoteFromJSON(json['quote']),
    };
}

export function DonationSwapDtoToJSON(value?: DonationSwapDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'to': value.to,
        'data': value.data,
        'value': value.value,
        'quote': DonationSwapDtoQuoteToJSON(value.quote),
    };
}

