/* tslint:disable */
/* eslint-disable */
/**
 * Endaoment API
 * The official Endaoment API & SDK endpoints
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FundSdkDto
 */
export interface FundSdkDto {
    /**
     * The fund's Endaoment id
     * @type {string}
     * @memberof FundSdkDto
     */
    id: string;
    /**
     * The fund's name
     * @type {string}
     * @memberof FundSdkDto
     */
    name: string;
    /**
     * The fund's contract address
     * @type {string}
     * @memberof FundSdkDto
     */
    contractAddress: string;
    /**
     * The fund's logo url
     * @type {string}
     * @memberof FundSdkDto
     */
    logoUrl: string | null;
    /**
     * The fund's description
     * @type {string}
     * @memberof FundSdkDto
     */
    description: string;
    /**
     * The fund's Endaoment url
     * @type {string}
     * @memberof FundSdkDto
     */
    endaomentUrl: string;
}

/**
 * Check if a given object implements the FundSdkDto interface.
 */
export function instanceOfFundSdkDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "contractAddress" in value;
    isInstance = isInstance && "logoUrl" in value;
    isInstance = isInstance && "description" in value;
    isInstance = isInstance && "endaomentUrl" in value;

    return isInstance;
}

export function FundSdkDtoFromJSON(json: any): FundSdkDto {
    return FundSdkDtoFromJSONTyped(json, false);
}

export function FundSdkDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): FundSdkDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'contractAddress': json['contractAddress'],
        'logoUrl': json['logoUrl'],
        'description': json['description'],
        'endaomentUrl': json['endaomentUrl'],
    };
}

export function FundSdkDtoToJSON(value?: FundSdkDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'contractAddress': value.contractAddress,
        'logoUrl': value.logoUrl,
        'description': value.description,
        'endaomentUrl': value.endaomentUrl,
    };
}

