/* tslint:disable */
/* eslint-disable */
/**
 * Endaoment API
 * The official Endaoment API & SDK endpoints
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NdaoSdkTransaction
 */
export interface NdaoSdkTransaction {
    /**
     * The address this transaction will be sent to
     * @type {string}
     * @memberof NdaoSdkTransaction
     */
    to: string;
    /**
     * The data this transaction will send to the destination contract
     * @type {string}
     * @memberof NdaoSdkTransaction
     */
    data: string;
    /**
     * The ETH value, if any, this transaction will send along
     * @type {string}
     * @memberof NdaoSdkTransaction
     */
    value: string;
}

/**
 * Check if a given object implements the NdaoSdkTransaction interface.
 */
export function instanceOfNdaoSdkTransaction(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "to" in value;
    isInstance = isInstance && "data" in value;
    isInstance = isInstance && "value" in value;

    return isInstance;
}

export function NdaoSdkTransactionFromJSON(json: any): NdaoSdkTransaction {
    return NdaoSdkTransactionFromJSONTyped(json, false);
}

export function NdaoSdkTransactionFromJSONTyped(json: any, ignoreDiscriminator: boolean): NdaoSdkTransaction {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'to': json['to'],
        'data': json['data'],
        'value': json['value'],
    };
}

export function NdaoSdkTransactionToJSON(value?: NdaoSdkTransaction | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'to': value.to,
        'data': value.data,
        'value': value.value,
    };
}

