/* tslint:disable */
/* eslint-disable */
/**
 * Endaoment API
 * The official Endaoment API & SDK endpoints
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrgSdkDto
 */
export interface OrgSdkDto {
    /**
     * The org's Endaoment id
     * @type {string}
     * @memberof OrgSdkDto
     */
    id: string;
    /**
     * The org's name
     * @type {string}
     * @memberof OrgSdkDto
     */
    name: string;
    /**
     * The org's EIN
     * @type {string}
     * @memberof OrgSdkDto
     */
    ein: string;
    /**
     * The org's contract address
     * @type {string}
     * @memberof OrgSdkDto
     */
    contractAddress: string;
    /**
     * The org's logo url
     * @type {string}
     * @memberof OrgSdkDto
     */
    logoUrl: string;
    /**
     * The org's NTEE code
     * @type {string}
     * @memberof OrgSdkDto
     */
    nteeCode: string;
    /**
     * The org's NTEE description
     * @type {string}
     * @memberof OrgSdkDto
     */
    nteeDescription: string;
    /**
     * The org's description
     * @type {string}
     * @memberof OrgSdkDto
     */
    description: string | null;
    /**
     * The org's Endaoment url
     * @type {string}
     * @memberof OrgSdkDto
     */
    endaomentUrl: string;
}

/**
 * Check if a given object implements the OrgSdkDto interface.
 */
export function instanceOfOrgSdkDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "ein" in value;
    isInstance = isInstance && "contractAddress" in value;
    isInstance = isInstance && "logoUrl" in value;
    isInstance = isInstance && "nteeCode" in value;
    isInstance = isInstance && "nteeDescription" in value;
    isInstance = isInstance && "description" in value;
    isInstance = isInstance && "endaomentUrl" in value;

    return isInstance;
}

export function OrgSdkDtoFromJSON(json: any): OrgSdkDto {
    return OrgSdkDtoFromJSONTyped(json, false);
}

export function OrgSdkDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrgSdkDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'ein': json['ein'],
        'contractAddress': json['contractAddress'],
        'logoUrl': json['logoUrl'],
        'nteeCode': json['nteeCode'],
        'nteeDescription': json['nteeDescription'],
        'description': json['description'],
        'endaomentUrl': json['endaomentUrl'],
    };
}

export function OrgSdkDtoToJSON(value?: OrgSdkDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'ein': value.ein,
        'contractAddress': value.contractAddress,
        'logoUrl': value.logoUrl,
        'nteeCode': value.nteeCode,
        'nteeDescription': value.nteeDescription,
        'description': value.description,
        'endaomentUrl': value.endaomentUrl,
    };
}

