/* tslint:disable */
/* eslint-disable */
/**
 * Endaoment API
 * The official Endaoment API & SDK endpoints
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SwapQuote
 */
export interface SwapQuote {
    /**
     * The price impact this swap will produce
     * @type {number}
     * @memberof SwapQuote
     */
    priceImpact: number;
    /**
     * The expected output for this swap
     * @type {string}
     * @memberof SwapQuote
     */
    expectedUsdc: string;
    /**
     * The minimum value this swap will output
     * @type {string}
     * @memberof SwapQuote
     */
    minimumTolerableUsdc: string;
}

/**
 * Check if a given object implements the SwapQuote interface.
 */
export function instanceOfSwapQuote(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "priceImpact" in value;
    isInstance = isInstance && "expectedUsdc" in value;
    isInstance = isInstance && "minimumTolerableUsdc" in value;

    return isInstance;
}

export function SwapQuoteFromJSON(json: any): SwapQuote {
    return SwapQuoteFromJSONTyped(json, false);
}

export function SwapQuoteFromJSONTyped(json: any, ignoreDiscriminator: boolean): SwapQuote {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'priceImpact': json['priceImpact'],
        'expectedUsdc': json['expectedUsdc'],
        'minimumTolerableUsdc': json['minimumTolerableUsdc'],
    };
}

export function SwapQuoteToJSON(value?: SwapQuote | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'priceImpact': value.priceImpact,
        'expectedUsdc': value.expectedUsdc,
        'minimumTolerableUsdc': value.minimumTolerableUsdc,
    };
}

